kind: RoleBinding
apiVersion: v1
metadata:
  name: system:deployer
  namespace: {{ .Release.Namespace }}
userNames:
- system:serviceaccount:{{ .Release.Namespace }}:deployer
groupNames: 
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: deployer
roleRef:
  name: system:deployer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-rb-admin
  namespace: {{ .Release.Namespace }}
subjects:
- kind: Group
  name: system:authenticated
roleRef:
  kind: ClusterRole
  name: admin