apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: {{ .Release.Name }}-chrome
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 60
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    name: {{ .Release.Name }}-chrome
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-chrome
    spec:
      containers:
      - name: {{ .Release.Name }}-chrome
        image: elgalu/selenium:3.141.59-p21
        imagePullPolicy: Always
        env:
        - name: NOVNC
          value: 'true'
        - name: SELENIUM_HUB_HOST
          value: {{ .Release.Name }}-selenium-hub
        - name: SELENIUM_HUB_PORT
          value: '4444'
        - name: SCREEN_WIDTH
          value: '1300'
        - name: SCREEN_HEIGHT
          value: '999'    
        - name: VIDEO
          value: 'false'                  
        - name: GRID
          value: 'false'
        - name: CHROME
          value: 'true'          
        - name: FIREFOX
          value: 'false' 
        ports:
        - containerPort: 5900
          protocol: TCP
        - containerPort: 6081
          protocol: TCP          
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /dev/shm
          name: chrome-dev
      dnsPolicy: ClusterFirst 
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sa-{{ .Release.Name }}
      serviceAccountName: sa-{{ .Release.Name }}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
---  
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-chrome
  name: {{ .Release.Name }}-chrome
  namespace: {{ .Release.Namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: "tcp-5900"
    port: 25900
    protocol: TCP
    targetPort: 5900
  - name: "tcp-6081"
    port: 26080
    protocol: TCP
    targetPort: 6081
  selector:
    name: {{ .Release.Name }}-chrome
  sessionAffinity: None
  type: NodePort
