apiVersion: v1
kind: DeploymentConfig
metadata:
  name: {{ .Release.Name }}-selenium-hub
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 60
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    name: {{ .Release.Name }}-selenium-hub
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-selenium-hub
    spec:
      containers:
      - image: selenium/hub:3.141.59-palladium
        imagePullPolicy: Always
        name: {{ .Release.Name }}-selenium-hub
        env:
        - name: GRID_MAX_SESSION
          value: '20'
        - name: GRID_DEBUG
          value: 'true'
        - name: GRID_BROWSER_TIMEOUT
          value: '3000'
        - name: GRID_TIMEOUT
          value: '3000'
        ports:
        - containerPort: 4444
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sa-{{ .Release.Name }}
      serviceAccountName: sa-{{ .Release.Name }}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: {{ .Release.Name }}-selenium-hub
  name: {{ .Release.Name }}-selenium-hub
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "tcp-4444"
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    name: {{ .Release.Name }}-selenium-hub
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    name: {{ .Release.Name }}-selenium-hub
  name: {{ .Release.Name }}-selenium-hub
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: "tcp-4444"
  to:
    kind: Service
    name: {{ .Release.Name }}-selenium-hub
    weight: 100
  wildcardPolicy: None
